// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 44.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class AppAssets {
  static const String package = 'callmobile';

  static const String bg_png = 'images/bg/bg.png';

  static const String bg_avatar_png = 'images/bg/bg_avatar.png';

  static const String bg_banner_png = 'images/bg/bg_banner.png';

  static const String bg_cover_png = 'images/bg/bg_cover.png';

  static const String bg_fan_avatar_png = 'images/bg/bg_fan_avatar.png';

  static const String logo_png = 'images/bg/logo.png';

  static const String ic_arrow_down_png = 'images/icon/ic_arrow_down.png';

  static const String ic_arrow_right_svg = 'images/icon/ic_arrow_right.svg';

  static const String ic_back_svg = 'images/icon/ic_back.svg';

  static const String ic_back_2_svg = 'images/icon/ic_back_2.svg';

  static const String ic_battery_png = 'images/icon/ic_battery.png';

  static const String ic_book_png = 'images/icon/ic_book.png';

  static const String ic_calendar_png = 'images/icon/ic_calendar.png';

  static const String ic_calendar_svg = 'images/icon/ic_calendar.svg';

  static const String ic_call_svg = 'images/icon/ic_call.svg';

  static const String ic_call_calling_svg = 'images/icon/ic_call_calling.svg';

  static const String ic_call_cancel_svg = 'images/icon/ic_call_cancel.svg';

  static const String ic_call_finish_svg = 'images/icon/ic_call_finish.svg';

  static const String ic_call_new_svg = 'images/icon/ic_call_new.svg';

  static const String ic_check_svg = 'images/icon/ic_check.svg';

  static const String ic_coin_png = 'images/icon/ic_coin.png';

  static const String ic_coin_svg = 'images/icon/ic_coin.svg';

  static const String ic_coin_3d_png = 'images/icon/ic_coin_3d.png';

  static const String ic_cry_png = 'images/icon/ic_cry.png';

  static const String ic_edit_svg = 'images/icon/ic_edit.svg';

  static const String ic_end_call_svg = 'images/icon/ic_end_call.svg';

  static const String ic_home_svg = 'images/icon/ic_home.svg';

  static const String ic_logout_svg = 'images/icon/ic_logout.svg';

  static const String ic_menu_svg = 'images/icon/ic_menu.svg';

  static const String ic_point_svg_svg = 'images/icon/ic_point.svg.svg';

  static const String ic_ranking_png = 'images/icon/ic_ranking.png';

  static const String ic_sad_png = 'images/icon/ic_sad.png';

  static const String ic_search_svg = 'images/icon/ic_search.svg';

  static const String ic_setting_svg = 'images/icon/ic_setting.svg';

  static const String ic_sound_effect_png = 'images/icon/ic_sound_effect.png';

  static const String ic_sound_on_svg = 'images/icon/ic_sound_on.svg';

  static const String ic_success_svg = 'images/icon/ic_success.svg';

  static const String ic_target_png = 'images/icon/ic_target.png';

  static const String ic_user_png = 'images/icon/ic_user.png';

  static const String ic_voice_off_svg = 'images/icon/ic_voice_off.svg';

  static const String ic_voice_on_svg = 'images/icon/ic_voice_on.svg';

  static const String ic_wait_png = 'images/icon/ic_wait.png';

  static const String ic_waiting_png = 'images/icon/ic_waiting.png';

  static const String ic_waiting_menu_svg = 'images/icon/ic_waiting_menu.svg';

  static const String ic_renew_svg = 'images/icon/ic_renew.svg';

  static const String ic_star_png = 'images/icon/ic_star.png';

  static const String ic_schedule_png = 'images/icon/ic_schedule.png';

  static const String ic_setting_png = 'images/icon/ic_setting.png';

  static const String ic_up_png = 'images/icon/ic_up.png';

  static const String ic_down_png = 'images/icon/ic_down.png';

  static const String ic_call_list_png = 'images/icon/ic_call_list.png';

  static const String ic_right_double_svg = 'images/icon/ic_right_double.svg';

  static const String ic_waiting_group_png = 'images/icon/ic_waiting_group.png';

  static const String ic_upload_svg = 'images/icon/ic_upload.svg';

  static const String ic_rank_5_svg = 'images/icon/ic_rank_5.svg';

  static const String ic_close_svg = 'images/icon/ic_close.svg';
}
